version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ong
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqls/:/docker-entrypoint-initdb.d/
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: