SET NAMES 'utf8mb4';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
USE `ong` ;

-- CREATE CONSTRAINTS
-- PRIMARY KEYS
ALTER TABLE `doador` ADD CONSTRAINT PK_ID_Doador PRIMARY KEY (`ID_Doador`);
ALTER TABLE `doacao` ADD CONSTRAINT PK_ID_Doacao PRIMARY KEY (`ID_Doacao`);
ALTER TABLE `entrega` ADD CONSTRAINT PK_ID_Entrega PRIMARY KEY (`ID_Entrega`);
ALTER TABLE `evento` ADD CONSTRAINT PK_ID_Evento PRIMARY KEY (`ID_Evento`);
ALTER TABLE `instituicao` ADD CONSTRAINT PK_Inst_CNPJ PRIMARY KEY (`CNPJ`);
ALTER TABLE `item` ADD CONSTRAINT PK_ID_Item PRIMARY KEY (`ID_Item`);
ALTER TABLE `receptor` ADD CONSTRAINT PK_Receptor_CPF PRIMARY KEY (`CPF`);
ALTER TABLE `voluntario` ADD CONSTRAINT PK_Voluntario_CPF PRIMARY KEY (`CPF`);
-- FOREIGN KEYS
ALTER TABLE `doacao` ADD CONSTRAINT FK_Doador FOREIGN KEY (`Doador`) REFERENCES `ong`.`doador`(`ID_Doador`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `entrega` ADD CONSTRAINT FK_Evento FOREIGN KEY (`Evento`) REFERENCES `ong`.`evento`(`ID_Evento`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `entrega` ADD CONSTRAINT FK_Receptor FOREIGN KEY (`Receptor`) REFERENCES `ong`.`receptor`(`CPF`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `item_da_entrega` ADD CONSTRAINT FK_Item FOREIGN KEY (`ID_Item`) REFERENCES `ong`.`item`(`ID_Item`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `item_da_entrega` ADD CONSTRAINT FK_Entrega FOREIGN KEY (`ID_Entrega`) REFERENCES `ong`.`entrega`(`ID_Entrega`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `item_doado` ADD CONSTRAINT FK_Doado_Item FOREIGN KEY (`ID_Item`) REFERENCES `ong`.`item`(`ID_Item`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `item_doado` ADD CONSTRAINT FK_Doacao FOREIGN KEY (`ID_Doacao`) REFERENCES `ong`.`doacao`(`ID_Doacao`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `voluntario` ADD CONSTRAINT FK_Instituicao FOREIGN KEY (`Instituicao`) REFERENCES `ong`.`instituicao`(`CNPJ`) ON DELETE SET NULL ON UPDATE CASCADE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;